# Site Settings
title: Det 001

# Remote theme
remote_theme: jekyll/minima@v2.5.1  # Use static version - github page directs this to avoid breaking with upcoming changes

# Specific Theme Config Options
minima:
  skin: auto  # Options: 'classic' (light), 'dark' (forced dark), or 'auto' (system-based switching)
  
# Color mode settings
color-mode: auto        # Respect OS light/dark mode
color-mode-toggle: true # Show toggle in the corner

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed         # Optional: RSS feed
  - jekyll-remote-theme # Fetch theme from github

